Update nansat_wkv.yml
nansencenter/nersc-vocabularies pull request #7
Opened 2021-01-25 15:56 UTC by aanersc

2021-01-26 08:41 UTC, akorosov requested changes

2021-01-26 08:41 UTC, akorosov commented on nansat_wkv.yml
> +  short_name: U
```suggestion
  short_name: V
  units: m s-1
```

2021-01-26 08:41 UTC, akorosov commented on nansat_wkv.yml
> +  short_name: V
```suggestion
  short_name: U
  units: m s-1
```

2021-01-26 08:48 UTC, aanersc commented
@akorosov I have committed them.

2021-01-29 14:52 UTC, akorosov requested changes

2021-01-29 14:52 UTC, akorosov commented on nansat_wkv.yml
> +  units: m s-1
Oops, now the units are duplicated. Both here and below. I accidentally included them in the suggestion.
```suggestion
```

2021-01-29 14:52 UTC, akorosov commented on nansat_wkv.yml
> +  units: m s-1
```suggestion
```

2021-02-03 15:01 UTC, akorosov approved these changes

2021-02-03 15:01 UTC, merged